/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.neohope.avro.test;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public interface JustATest {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"JustATest\",\"namespace\":\"com.neohope.avro.test\",\"types\":[{\"type\":\"record\",\"name\":\"Person\",\"fields\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"age\",\"type\":\"int\"},{\"name\":\"sex\",\"type\":\"string\"},{\"name\":\"address\",\"type\":\"string\"}]}],\"messages\":{\"SayHelloTo\":{\"request\":[{\"name\":\"person\",\"type\":\"Person\"}],\"response\":\"string\"},\"Add\":{\"request\":[{\"name\":\"a\",\"type\":\"int\"},{\"name\":\"b\",\"type\":\"int\"}],\"response\":\"int\"}}}");
  /**
   */
  java.lang.CharSequence SayHelloTo(com.neohope.avro.test.Person person) throws org.apache.avro.AvroRemoteException;
  /**
   */
  int Add(int a, int b) throws org.apache.avro.AvroRemoteException;

  @SuppressWarnings("all")
  public interface Callback extends JustATest {
    public static final org.apache.avro.Protocol PROTOCOL = com.neohope.avro.test.JustATest.PROTOCOL;
    /**
     * @throws java.io.IOException The async call could not be completed.
     */
    void SayHelloTo(com.neohope.avro.test.Person person, org.apache.avro.ipc.Callback<java.lang.CharSequence> callback) throws java.io.IOException;
    /**
     * @throws java.io.IOException The async call could not be completed.
     */
    void Add(int a, int b, org.apache.avro.ipc.Callback<java.lang.Integer> callback) throws java.io.IOException;
  }
}